import Head from 'next/head'
import Image from 'next/image'

export default function Home(props) {
  return (
    <>
      <Head>
        <title>NextJS 13 ChatGPT Locale Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-indigo-800 h-screen flex text-white">
        {JSON.stringify(props, null, 2)}
        <div className="w-full md:w-[1200px] bg-indigo-700 mx-auto md:px-10 md:py-10">
          <h1 className="font-bold text-2xl">NextJS 13 ChatGPT Locale Example</h1>
          <div className="p-4 border-2 border-gray-400 rounded-md focus-within:shadow-blue relative flex w-full">
            <select id="4cfc454f-8760-24b1-fac9-f84055b6e47c" className="focus:outline-none w-full bg-transparent text-blue-200" name="reference" placeholder="Select Language">
              <option className="bg-indigo-700" disabled="">** Select Language **</option>
            </select>
          </div>
        </div>
      </div>
    </>
  )
}

export async function getStaticProps({ locale }) {

  return {
    props: {
      locale
    },
    revalidate: 10
  }
}